# Visualização de dados

## Instalando e importando Dependêcias

In [ ]:
%pip install pandas 
%pip install lxml
%pip install openpyxl
%pip install html5lib
%pip install beautifulsoup4

import pandas as pd

In [8]:
df_eletric = pd.read_csv('https://raw.githubusercontent.com/ejgao/Time-Series-Datasets/master/Electric_Production.csv')

In [9]:
df_eletric.head()

       DATE  IPG2211A2N
0  1/1/1985     72.5052
1  2/1/1985     70.6720
2  3/1/1985     62.4502
3  4/1/1985     57.4714
4  5/1/1985     55.3151

In [10]:
df_eletric.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   DATE        397 non-null    object
 1   IPG2211A2N  397 non-null    float64
dtypes: float64(1), object(1)
memory usage: 6.3+ KB

In [16]:
df_eletric['DATE'] = pd.to_datetime(df_eletric['DATE'], dayfirst=True)

In [17]:
df_eletric

          DATE  IPG2211A2N
0   1985-01-01     72.5052
1   1985-01-02     70.6720
2   1985-01-03     62.4502
3   1985-01-04     57.4714
4   1985-01-05     55.3151
..         ...         ...
392 2017-01-09     98.6154
393 2017-01-10     93.6137
394 2017-01-11     97.3359
395 2017-01-12    114.7212
396 2018-01-01    129.4048

[397 rows x 2 columns]