# Leitura e Escrita de arquivos

## Instalando e importando Dependêcias

In [1]:
%pip install pandas 
import pandas as pd

## Carregando um arquivo CSV

In [5]:
df = pd.read_csv('./components/files/atv1test1.csv', encoding='latin1', sep = ';')

In [6]:
df

    Nome  Idade       Sexo
0   João     21  Masculino
1  Maria     18   Feminino
2  Pedro     34  Masculino
3  Joana     25   Feminino

## Carregando um arquivo XLSX
### Necessário a instalação do **openpyxl**
%pip install openpyxl

In [ ]:
df = pd.read_excel('./components/files/atv1test1.xlsx')

Defaulting to user installation because normal site-packages is not writeable
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.9/250.9 KB 4.4 MB/s eta 0:00:00[31m3.6 MB/s eta 0:00:01
Collecting et-xmlfile
  Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [9]:
df

    Nome  Idade       Sexo
0   João     21  Masculino
1  Maria     18   Feminino
2  Pedro     34  Masculino
3  Joana     25   Feminino

## Carregando um arquivo da WIKI
### Necessário a instalação do **lxml package**
%pip install lxml

In [17]:
tabela_wiki = pd.read_html('https://en.wikipedia.org/wiki/List_of_Pok%C3%A9mon')

In [20]:
type(tabela_wiki)

print(f'Total de tabelas {len(tabela_wiki)}')

Todtal de tabelas 18

In [25]:
tabela_wiki[2]

              Generation I                                 Generation II  \
                     Dex #                   Name                  Dex #
0                        1             BulbasaurS                    152
1                        2                Ivysaur                    153
2                        3               Venusaur                    154
3                        4            CharmanderS                    155
4                        5             Charmeleon                    156
..                     ...                    ...                    ...
151  No additional Pokémon  No additional Pokémon  No additional Pokémon
152  No additional Pokémon  No additional Pokémon  No additional Pokémon
153  No additional Pokémon  No additional Pokémon  No additional Pokémon
154  No additional Pokémon  No additional Pokémon  No additional Pokémon
155  No additional Pokémon  No additional Pokémon  No additional Pokémon

                                   Generation III                         \
                      Name                  Dex #                   Name
0               ChikoritaS                    252               TreeckoS
1                  Bayleef                    253                Grovyle
2                 Meganium                    254               Sceptile
3               CyndaquilS                    255               TorchicS
4                  Quilava                    256              Combusken
..                     ...                    ...                    ...
151  No additional Pokémon  No additional Pokémon  No additional Pokémon
152  No additional Pokémon  No additional Pokémon  No additional Pokémon
153  No additional Pokémon  No additional Pokémon  No additional Pokémon
154  No additional Pokémon  No additional Pokémon  No additional Pokémon
155  No additional Pokémon  No additional Pokémon  No additional Pokémon

             Generation IV                        Generation V             \
                     Dex #                   Name        Dex #       Name
0                      387               TurtwigS          494   VictiniM
1                      388                 Grotle          495     SnivyS
2                      389               Torterra          496    Servine
3                      390              ChimcharS          497  Serperior
4                      391               Monferno          498     TepigS
..                     ...                    ...          ...        ...
151  No additional Pokémon  No additional Pokémon          645  LandorusL
152  No additional Pokémon  No additional Pokémon          646    KyuremL
153  No additional Pokémon  No additional Pokémon          647    KeldeoM
154  No additional Pokémon  No additional Pokémon          648  MeloettaM
155  No additional Pokémon  No additional Pokémon          649  GenesectM

             Generation VI                                Generation VII  \
                     Dex #                   Name                  Dex #
0                      650               ChespinS                    722
1                      651              Quilladin                    723
2                      652             Chesnaught                    724
3                      653              FennekinS                    725
4                      654                Braixen                    726
..                     ...                    ...                    ...
151  No additional Pokémon  No additional Pokémon  No additional Pokémon
152  No additional Pokémon  No additional Pokémon  No additional Pokémon
153  No additional Pokémon  No additional Pokémon  No additional Pokémon
154  No additional Pokémon  No additional Pokémon  No additional Pokémon
155  No additional Pokémon  No additional Pokémon  No additional Pokémon

                                  Generation VIII                         \
                      Name                  Dex #                   Name
0                  RowletS                    810               GrookeyS
1                  Dartrix                    811               Thwackey
2                Decidueye                    812              Rillaboom
3                  LittenS                    813             ScorbunnyS
4                 Torracat                    814                 Raboot
..                     ...                    ...                    ...
151  No additional Pokémon  No additional Pokémon  No additional Pokémon
152  No additional Pokémon  No additional Pokémon  No additional Pokémon
153  No additional Pokémon  No additional Pokémon  No additional Pokémon
154  No additional Pokémon  No additional Pokémon  No additional Pokémon
155  No additional Pokémon  No additional Pokémon  No additional Pokémon

                                      Generation IX  \
                                              Dex #
0                                               906
1                                               907
2                                               908
3                                               909
4                                               910
..                                              ...
151  No additional Pokémon (as of 14 December 2023)
152  No additional Pokémon (as of 14 December 2023)
153  No additional Pokémon (as of 14 December 2023)
154  No additional Pokémon (as of 14 December 2023)
155  No additional Pokémon (as of 14 December 2023)


                                               Name
0                                       SprigatitoS
1                                         Floragato
2                                       Meowscarada
3                                          FuecocoS
4                                          Crocalor
..                                              ...
151  No additional Pokémon (as of 14 December 2023)
152  No additional Pokémon (as of 14 December 2023)
153  No additional Pokémon (as of 14 December 2023)
154  No additional Pokémon (as of 14 December 2023)
155  No additional Pokémon (as of 14 December 2023)

[156 rows x 18 columns]

## Procurar Uma tabela por texto específico
### Necessário a intalação do **beautifulsoup4**
%pip install beautifulsoup4

In [ ]:

tabela_wiki_species = pd.read_html('https://en.wikipedia.org/wiki/List_of_Pok%C3%A9mon', match='Pokémon species glossary')

In [32]:
tabela_wiki_species[0]

             Key                                                     \
  Color / Letter                                            Meaning
0              S  Starter Pokémon (also known as First Partner P...
1              F                                 Fossil Pokémon[32]
2              B                                   Baby Pokémon[33]
3              L                                  Legendary Pokémon
4              M                                   Mythical Pokémon
5              U                                        Ultra Beast
6              P                                    Paradox Pokémon

                                                                         \
                                         Description Unnamed: 3_level_1
0  The first Pokémon a player is able to obtain i...                NaN
1  Ancient Pokémon only obtained by resurrecting ...                NaN
2  Infant Pokémon primarily obtained by breeding ...                NaN
3  Powerful Pokémon associated with the legends a...                NaN
4  Pokémon only obtainable through rare circumsta...                NaN
5            Certain Pokémon from another dimension.                NaN
6  Pokémon resembling ancient or futuristic relat...                NaN


  Unnamed: 4_level_1
0                NaN
1                NaN
2                NaN
3                NaN
4                NaN
5                NaN
6                NaN