# Seleção e Filtragem de dados

## Instalando e importando Dependêcias

In [ ]:
%pip install pandas 
import pandas as pd

## Definição de um **DF** e leitura dos arquivos **HTML**

In [4]:
df = pd.read_html('https://gist.github.com/DamiaoArth/ace0ed235f37244ef5d883e0b6354744')[0]

In [5]:
df

,Unnamed: 0,No,Branch_Code,Original_Name,Name,Generation,Height,Weight,Type1,Type2,...,SP_Attack,SP_Defense,Speed,Total,E_HP,E_Attack,E_Defense,E_SP_Attack,E_SP_Defense,E_Speed
0,NaN,1,1_0,Bulbasaur,Bulbasaur,1,0.7,6.9,Grass,Poison,...,65,65,45,318,0,0,0,1,0,0
1,NaN,2,2_0,Ivysaur,Ivysaur,1,1.0,13.0,Grass,Poison,...,80,80,60,405,0,0,0,1,1,0
2,NaN,3,3_0,Venusaur,Venusaur,1,2.0,100.0,Grass,Poison,...,100,100,80,525,0,0,0,2,1,0
3,NaN,3,3_1,Venusaur,Mega Venusaur,1,2.4,155.5,Grass,Poison,...,122,120,80,625,0,0,0,2,1,0
4,NaN,4,4_0,Charmander,Charmander,1,0.6,8.5,Fire,NaN,...,60,50,65,309,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1198,NaN,1006,1006_0,Iron Valiant,Iron Valiant,9,1.4,35.0,Fairy,Fighting,...,120,60,116,590,0,3,0,0,0,0
1199,NaN,1007,1007_0,Koraidon,Koraidon,9,2.5,303.0,Fighting,Dragon,...,85,100,135,670,0,3,0,0,0,0
1200,NaN,1008,1008_0,Miraidon,Miraidon,9,3.5,240.0,Electric,Dragon,...,135,115,135,670,0,0,0,3,0,0
1201,NaN,1009,1009_0,Walking Wake,Walking Wake,9,3.5,280.0,Water,Dragon,...,125,83,109,590,0,0,0,3,0,0
1202,NaN,1010,1010_0,Iron Leaves,Iron Leaves,9,1.5,125.0,Grass,Psychic,...,70,108,104,590,0,3,0,0,0,0

In [28]:
coluna = df['Name']

colunas= df[['Name', 'Type1', 'Attack']]

linhas = df[df['Attack'] > 100]

# Filtrar HP
HP = df.loc[df['HP'] > 150, ['Name', 'Type1', 'Type2', 'HP']].sort_values(by='HP', ascending=False)

# Filtrar Attack
Attack = df.loc[df['Attack'] > 150, ['Name', 'Type1', 'Type2', 'Attack']].sort_values(by='Attack', ascending=False)

# Filtrar Defense
Defense = df.loc[df['Defense'] > 150, ['Name', 'Type1', 'Type2', 'Defense']].sort_values(by='Defense', ascending=False)

# Filtrar Special Attack (SP_Attack)
SP_Attack = df.loc[df['SP_Attack'] > 150, ['Name', 'Type1', 'Type2', 'SP_Attack']].sort_values(by='SP_Attack', ascending=False)

# Filtrar Special Defense (SP_Defense)
SP_Defense = df.loc[df['SP_Defense'] > 150, ['Name', 'Type1', 'Type2', 'SP_Defense']].sort_values(by='SP_Defense', ascending=False)

# Filtrar Speed
Speed = df.loc[df['Speed'] > 150, ['Name', 'Type1', 'Type2', 'Speed']].sort_values(by='Speed', ascending=False)

## Busca Personalizada

In [32]:
#colunas
#coluna
#linhas

#HP
#Attack
#Defense
#SP_Attack
#SP_Defense
#Speed

                              Name    Type1     Type2  Attack
199                  Mega Mewtwo X  Psychic  Fighting     190
272                 Mega Heracross      Bug  Fighting     185
965                        Kartana    Grass     Steel     181
471                 Primal Groudon   Ground      Fire     180
473                  Mega Rayquaza   Dragon    Flying     180
476             Deoxys Attack Form  Psychic       NaN     180
546                  Mega Garchomp   Dragon    Ground     170
781                   Black Kyurem   Dragon       Ice     170
970                 Ultra Necrozma  Psychic    Dragon     167
1077             Calyrex Ice Rider  Psychic       Ice     165
579                   Mega Gallade  Psychic  Fighting     165
501                      Rampardos     Rock       NaN     165
434                   Mega Banette    Ghost       NaN     165
310                 Mega Tyranitar     Rock      Dark     164
357                        Slaking   Normal       NaN     160
321                  Mega Blaziken     Fire  Fighting     160
873                  Unbound Hoopa  Psychic      Dark     160
871                   Mega Diancie     Rock     Fairy     160
677   Galarian Darmanitan Zen-Mode      Ice      Fire     160
597                      Regigigas   Normal       NaN     160
1152             Palafin Hero Form    Water       NaN     160
968             Dusk Mane Necrozma  Psychic     Steel     157
174                  Mega Gyarados    Water      Dark     155
167                    Mega Pinsir      Bug    Flying     155

## Inspecionando Informaçõs (Data Type)

In [ ]:
df.info()